"""Add admin table

Revision ID: 0003
Revises: 0002
Create Date: 2024-12-19 12:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID администратора",
        ),
        sa.Column(
            "telegram_id",
            sa.Integer(),
            nullable=False,
            comment="Telegram ID администратора",
        ),
        sa.Column(
            "username",
            sa.String(length=255),
            nullable=True,
            comment="Telegram username администратора",
        ),
        sa.Column(
            "first_name",
            sa.String(length=255),
            nullable=True,
            comment="Имя администратора",
        ),
        sa.Column(
            "last_name",
            sa.String(length=255),
            nullable=True,
            comment="Фамилия администратора",
        ),
        sa.Column(
            "role",
            sa.String(length=50),
            nullable=False,
            comment="Роль администратора",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Активен ли администратор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "last_login",
            sa.DateTime(),
            nullable=True,
            comment="Последний вход",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_users")
    # ### end Alembic commands ###
